apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
      - name: stock-api
        image: <ACR_NAME>.azurecr.io/stock-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: ALPHAVANTAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: stock-secret
              key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: stock-api-service
spec:
  type: LoadBalancer
  selector:
    app: stock-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
